M_study/rails_p2p/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { sessions: 'users/sessions' }

  root to: "dummy#index"

  resources :rooms, only: %i[new create show] do
    get :recording_audio, :member
  end
end

M_study/rails_p2p/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

M_study/rails_p2p/app/models/recording.rb
class Recording < ApplicationRecord
  has_many :users_recordings, dependent: :destroy
  belongs_to :room

  def store_path
    Rails.root.join("audio/#{room_id}/#{id}/")
  end

  def synthesize_file_path
    store_path.join('1.wav').to_s
  end
end

M_study/rails_p2p/app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, autosave: false
  has_many :recordings

  def start_recording
    recordings.create
  end

  def now_recording
    recordings.last
  end
end

M_study/rails_p2p/app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :user
  belongs_to :room

  scope :online, -> { where.not(ws_connection_identifier: nil) }

  def solo_broadcasting_name
    "room_user:#{id}"
  end

  def online!(identifier)
    update!(ws_connection_identifier: identifier)
  end
end

M_study/rails_p2p/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :room_users
  has_many :rooms, through: :room_users

  def email_required?
    false
  end

  def will_save_change_to_email?
    false
  end
end

M_study/rails_p2p/app/models/users_recording.rb
class UsersRecording < ApplicationRecord
  belongs_to :user
  belongs_to :recording

  enum recording_status: { writing: 0, close: 1 }

  attribute :recording_status, :integer, default: :writing

  def wav_file_name
    "#{user_id}.wav"
  end
end

M_study/rails_p2p/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

M_study/rails_p2p/app/controllers/dummy_controller.rb
class DummyController < ApplicationController
  before_action :authenticate_user!

  def index; end
end

M_study/rails_p2p/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # todo room member validate to show / recording_audio

  def new
    @room_form = RoomForm.new(Room.new, current_user)
  end

  def create
    @room_form = RoomForm.new(
      Room.new,
      current_user,
      room_form_params
    )

    if @room_form.save
      redirect_to @room_form.model
    else
      render :new
    end
  end

  def show
    @room = Room.find(params[:id])
  end

  def recording_audio
    room = Room.find(params[:room_id])
    recording = room.recordings.find(params[:recording_id])

    send_data File.read(recording.synthesize_file_path)
  end

  private

  def room_form_params
    params.require(:room_form)
          .permit(:id, room_users_attributes: %i[id selected user_id])
  end
end

M_study/rails_p2p/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

M_study/rails_p2p/app/helpers/application_helper.rb
module ApplicationHelper
end

M_study/rails_p2p/app/helpers/dummy_helper.rb
module DummyHelper
end

M_study/rails_p2p/app/helpers/rooms_helper.rb
module RoomsHelper
end

M_study/rails_p2p/app/views/layouts/application.html.slim
doctype html
html
  head
    title RailsP2p
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'

  body

    p = "Hi, #{current_user&.login_id}"

    p.notice = notice
    p.alert = alert

    == yield

M_study/rails_p2p/app/views/rooms/create.html.slim
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

M_study/rails_p2p/app/views/rooms/new.html.slim
- if @room_form.errors.any?
  ul
    - @room_form.errors.full_messages.each do |msg|
      li = msg


= form_for @room_form, url: rooms_path do |f|
  ul
    = f.fields_for :room_users do |ff|
      li
        = ff.check_box :selected
        = ff.label :selected, ff.object.user.login_id
        = ff.hidden_field :id
        = ff.hidden_field :user_id
  = f.submit

M_study/rails_p2p/app/views/rooms/show.html.slim
.room
  .room-name
    | Room
    span#room-id = @room.id

  #video-chat
    .remote-video
      video#remote-video autoplay="" style="width: 500px; height: 400px;border: 1px solid #ddd;"

    div
      button#call-me call
      button#start-recording start
      button#stop-recording stop

  #recordings
    | Recordings
    .recording-list

sass:
  .room
    width: 500px;
    margin: 0 auto;
  div
    margin: 18px 0;